class WikipediaLanguage:

    def __init__(self, name : str, subdomain : str):
        self.name = str(name)
        self.subdomain = str(subdomain)



LANGUAGES = {
    'ABK' : WikipediaLanguage('Abkhazian', 'ab'),
    'ACH' : WikipediaLanguage('Acehnese', 'ace'),
    'ADG' : WikipediaLanguage('Adyghe', 'ady'),
    'AFR' : WikipediaLanguage('Afrikaans', 'af'),
    'ALB' : WikipediaLanguage('Albanian', 'sq'),
    'ALM' : WikipediaLanguage('Alemannic', 'als'),
    'AMH' : WikipediaLanguage('Amharic', 'am'),
    'AMS' : WikipediaLanguage('Amis', 'ami'),
    'ANG' : WikipediaLanguage('Angika', 'anp'),
    'ARB' : WikipediaLanguage('Arabic', 'ar'),
    'ARG' : WikipediaLanguage('Aragonese', 'an'),
    'AMC' : WikipediaLanguage('Aramaic', 'arc'),
    'ARM' : WikipediaLanguage('Armenian', 'hy'),
    'ARO' : WikipediaLanguage('Aromanian', 'roa-rup'),
    'ARP' : WikipediaLanguage('Arpitan', 'arp'),
    'ASS' : WikipediaLanguage('Assamese', 'as'),
    'AST' : WikipediaLanguage('Asturian', 'ast'),
    'ATK' : WikipediaLanguage('Atikamekw', 'atj'),
    'AVR' : WikipediaLanguage('Avaric', 'av'),
    'AWD' : WikipediaLanguage('Awadhi', 'awa'),
    'AYM' : WikipediaLanguage('Aymara', 'ay'),
    'AZE' : WikipediaLanguage('Azerbaijani', 'az'),
    'BAL' : WikipediaLanguage('Balinese', 'ban'),
    'BAM' : WikipediaLanguage('Bambara', 'bm'),
    'BNG' : WikipediaLanguage('Bengali', 'bn'),
    'BNJ' : WikipediaLanguage('Banjar', 'bjn'),
    'BSB' : WikipediaLanguage('Basa Banyumasan', 'map-bms'),
    'BSK' : WikipediaLanguage('Bashkir', 'ba'),
    'BSQ' : WikipediaLanguage('Basque', 'eu'),
    'BAV' : WikipediaLanguage('Bavarian', 'bar'),
    'BLR' : WikipediaLanguage('Belarusian', 'be'),
    'BHO' : WikipediaLanguage('Bhojpuri', 'bh'),
    'BSH' : WikipediaLanguage('Bishnupriya', 'bpy'),
    'BIS' : WikipediaLanguage('Bislama', 'bi'),
    'BIH' : WikipediaLanguage('Bosnian', 'bs'),
    'BRE' : WikipediaLanguage('Breton', 'br'),
    'BUG' : WikipediaLanguage('Buginese', 'bug'),
    'BUL' : WikipediaLanguage('Bulgarian', 'bg'),
    'BUR' : WikipediaLanguage('Burmese', 'my'),
    'CAN' : WikipediaLanguage('Cantonese', 'zh-yue'),
    'CAT' : WikipediaLanguage('Catalan', 'ca'),
    'CEB' : WikipediaLanguage('Cebuano', 'ceb'),
    'CBK' : WikipediaLanguage('Central Bikol', 'bcl'),
    'CKD' : WikipediaLanguage('Central Kurdish', 'ckb'),
    'CHM' : WikipediaLanguage('Chamorro', 'ch'),
    'CHV' : WikipediaLanguage('Chavacano', 'cbk-zam'),
    'CHE' : WikipediaLanguage('Chechen', 'ce'),
    'CHR' : WikipediaLanguage('Cherokee', 'chr'),
    'CHY' : WikipediaLanguage('Cheyenne', 'chy'),
    'CHN' : WikipediaLanguage('Chinese', 'zh'),
    'CSL' : WikipediaLanguage('Church Slavic', 'cu'),
    'CHU' : WikipediaLanguage('Chuvash', 'cv'),
    'CLG' : WikipediaLanguage('Colognian', 'ksh'),
    'COR' : WikipediaLanguage('Cornish', 'kw'),
    'CRS' : WikipediaLanguage('Corsican', 'co'),
    'CRE' : WikipediaLanguage('Cree', 'cr'),
    'CRT' : WikipediaLanguage('Crimean Tatar', 'crh'),
    'CRO' : WikipediaLanguage('Croatian', 'hr'),
    'CZE' : WikipediaLanguage('Czech', 'cs'),
    'DAG' : WikipediaLanguage('Dagbani', 'dag'),
    'DEN' : WikipediaLanguage('Danish', 'da'),
    'DIN' : WikipediaLanguage('Dinka', 'din'),
    'DHV' : WikipediaLanguage('Dhivehi', 'dv'),
    'DOT' : WikipediaLanguage('Doteli', 'dty'),
    'DUT' : WikipediaLanguage('Dutch', 'nl'),
    'DZG' : WikipediaLanguage('Dzongkha', 'dz'),
    'EMR' : WikipediaLanguage('Eastern Mari', 'mhr'),
    'EGY' : WikipediaLanguage('Egyptian Arabic', 'arz'),
    'ERO' : WikipediaLanguage('Emiliano-Romagnolo', 'eml'),
    'ENG' : WikipediaLanguage('English', 'en'),
    'ERZ' : WikipediaLanguage('Erzya', 'myv'),
    'ESR' : WikipediaLanguage('Esperanto', 'eo'),
    'EST' : WikipediaLanguage('Estonian', 'et'),
    'EWE' : WikipediaLanguage('Ewe', 'ee'),
    'EXT' : WikipediaLanguage('Extremaduran', 'ext'),
    'FAN' : WikipediaLanguage('Fanti', 'fat'),
    'FAR' : WikipediaLanguage('Faroese', 'fo'),
    'FIJ' : WikipediaLanguage('Fijian', 'fj'),
    'FIN' : WikipediaLanguage('Finnish', 'fi'),
    'FRF' : WikipediaLanguage('Frafra', 'gur'),
    'FRA' : WikipediaLanguage('French', 'fr'),
    'FRI' : WikipediaLanguage('Friulian', 'fur'),
    'FUL' : WikipediaLanguage('Fula', 'ff'),
    'GGZ' : WikipediaLanguage('Gagauz', 'gag'),
    'GAL' : WikipediaLanguage('Galician', 'gl'),
    'GAN' : WikipediaLanguage('Gan Chinese', 'gan'),
    'GAD' : WikipediaLanguage('Ganda', 'lg'),
    'GEO' : WikipediaLanguage('Georgian', 'ka'),
    'GER' : WikipediaLanguage('German', 'de'),
    'GHA' : WikipediaLanguage('Ghanaian Pidgin', 'gpe'),
    'GIL' : WikipediaLanguage('Gilaki', 'glk'),
    'GOK' : WikipediaLanguage('Goan Konkani', 'gom'),
    'GOR' : WikipediaLanguage('Gorontalo', 'gor'),
    'GOT' : WikipediaLanguage('Gothic', 'got'),
    'GRE' : WikipediaLanguage('Greek', 'el'),
    'GUA' : WikipediaLanguage('Guarani', 'gn'),
    'GUI' : WikipediaLanguage('Guianan Creole', 'gcr'),
    'GUJ' : WikipediaLanguage('Gujarati', 'gu'),
    'GUN' : WikipediaLanguage('Gun', 'guw'),
    'HTI' : WikipediaLanguage('Haitian Creole', 'ht'),
    'HKC' : WikipediaLanguage('Hakka Chinese', 'hak'),
    'HAU' : WikipediaLanguage('Hausa', 'ha'),
    'HAW' : WikipediaLanguage('Hawaiian', 'haw'),
    'HEB' : WikipediaLanguage('Hebrew', 'he'),
    'HIN' : WikipediaLanguage('Hindi', 'hi'),
    'HUN' : WikipediaLanguage('Hungarian', 'hu'),
    'ISL' : WikipediaLanguage('Icelandic', 'is'),
    'IDO' : WikipediaLanguage('Ido', 'io'),
    'IGB' : WikipediaLanguage('Igbo', 'ig'),
    'ILO' : WikipediaLanguage('Iloko', 'ilo'),
    'INS' : WikipediaLanguage('Inari Sami', 'smn'),
    'IDN' : WikipediaLanguage('Indonesian', 'id'),
    'ING' : WikipediaLanguage('Ingush', 'inh'),
    'INU' : WikipediaLanguage('Inuktitut', 'iu'),
    'INP' : WikipediaLanguage('Inupiaq', 'ik'),
    'IRL' : WikipediaLanguage('Irish', 'ga'),
    'ITA' : WikipediaLanguage('Italian', 'it'),
    'JAM' : WikipediaLanguage('Jamaican Creole English', 'jam'),
    'JPN' : WikipediaLanguage('Japanese', 'ja'),
    'JAV' : WikipediaLanguage('Javanese', 'jv'),
    'KAB' : WikipediaLanguage('Kabardian', 'kbd'),
    'KBY' : WikipediaLanguage('Kabyle', 'kab'),
    'KLA' : WikipediaLanguage('Kalaallisut', 'kl'),
    'KAL' : WikipediaLanguage('Kalmyk', 'xal'),
    'KAN' : WikipediaLanguage('Kannada', 'kn'),
    'KRK' : WikipediaLanguage('Kara-Kalpak', 'kaa'),
    'KRB' : WikipediaLanguage('Karachay-Balkar', 'krc'),
    'KSH' : WikipediaLanguage('Kashmiri', 'ks'),
    'KSB' : WikipediaLanguage('Kashubian', 'csb'),
    'KAZ' : WikipediaLanguage('Kazakh', 'kk'),
    'KHM' : WikipediaLanguage('Khmer', 'km'),
    'KIK' : WikipediaLanguage('Kikuyu', 'ki'),
    'KIN' : WikipediaLanguage('Kinyarwanda', 'rw'),
    'KOM' : WikipediaLanguage('Komi', 'kv'),
    'KOP' : WikipediaLanguage('Komi-Permyak', 'koi'),
    'KON' : WikipediaLanguage('Kongo', 'kg'),
    'KOR' : WikipediaLanguage('Korean', 'ko'),
    'KOT' : WikipediaLanguage('Kotava', 'avk'),
    'KUR' : WikipediaLanguage('Kurdish', 'ku'),
    'KYG' : WikipediaLanguage('Kyrgyz', 'ky'),
    'LAD' : WikipediaLanguage('Ladin', 'lld'),
    'LAK' : WikipediaLanguage('Lak', 'lbe'),
    'LAO' : WikipediaLanguage('Lao', 'lo'),
    'LTG' : WikipediaLanguage('Latgalian', 'ltg'),
    'LAT' : WikipediaLanguage('Latin', 'la'),
    'LVA' : WikipediaLanguage('Latvian', 'lv'),
    'LEZ' : WikipediaLanguage('Lezghian', 'lez'),
    'LIG' : WikipediaLanguage('Ligurian', 'lij'),
    'LIM' : WikipediaLanguage('Limburgish', 'li'),
    'LIN' : WikipediaLanguage('Lingala', 'ln'),
    'LTU' : WikipediaLanguage('Lithuanian', 'lt'),
    'LVK' : WikipediaLanguage('Livvi-Karelian', 'olo'),
    'LOJ' : WikipediaLanguage('Lojban', 'jbo'),
    'LOM' : WikipediaLanguage('Lombard', 'lmo'),
    'LGE' : WikipediaLanguage('Low German', 'nds'),
    'LSX' : WikipediaLanguage('Low Saxon', 'nds-nl'),
    'LSO' : WikipediaLanguage('Lower Sorbian', 'dsb'),
    'LUX' : WikipediaLanguage('Luxembourgish', 'lb'),
    'MKD' : WikipediaLanguage('Macedonian', 'mk'),
    'MAD' : WikipediaLanguage('Madurese', 'mad'),
    'MAI' : WikipediaLanguage('Maithili', 'mai'),
    'MLG' : WikipediaLanguage('Malagasy', 'mg'),
    'MAL' : WikipediaLanguage('Malay', 'ms'),
    'MLY' : WikipediaLanguage('Malayalam', 'ml'),
    'MLT' : WikipediaLanguage('Maltese', 'mt'),
    'MNP' : WikipediaLanguage('Manipuri', 'bpy'),
    'MAX' : WikipediaLanguage('Manx', 'gv'),
    'MAO' : WikipediaLanguage('Maori', 'mi'),
    'MTH' : WikipediaLanguage('Marathi', 'mr'),
    'MAZ' : WikipediaLanguage('Mazanderani', 'mzn'),
    'MNC' : WikipediaLanguage('Min Nan Chinese', 'zh-min-nan'),
    'MNK' : WikipediaLanguage('Minangkabau', 'min'),
    'MIG' : WikipediaLanguage('Mingrelian', 'xmf'),
    'MIR' : WikipediaLanguage('Mirandese', 'mwl'),
    'MOK' : WikipediaLanguage('Moksha', 'mdf'),
    'MON' : WikipediaLanguage('Mon', 'mnw'),
    'MGL' : WikipediaLanguage('Mongolian', 'mn'),
    'MAR' : WikipediaLanguage('Moroccan Arabic', 'ary'),
    'NKO' : WikipediaLanguage('N\'Ko', 'nqo'),
    'NAH' : WikipediaLanguage('Nahuatl', 'nah'),
    'NAV' : WikipediaLanguage('Navajo', 'nv'),
    'NAP' : WikipediaLanguage('Neapolitan', 'nap'),
    'NPL' : WikipediaLanguage('Nepali', 'ne'),
    'NEW' : WikipediaLanguage('Newari', 'new'),
    'NIA' : WikipediaLanguage('Nias', 'nia'),
    'NGA' : WikipediaLanguage('Nigerian Pidgin', 'pcm'),
    'NPT' : WikipediaLanguage('Norfuk/Pitkern', 'pih'),
    'NRM' : WikipediaLanguage('Norman', 'nrm'),
    'NFR' : WikipediaLanguage('Northern Frisian', 'frr'),
    'NSA' : WikipediaLanguage('Northern Sami', 'se'),
    'NSO' : WikipediaLanguage('Northern Sotho', 'nso'),
    'NOR' : WikipediaLanguage('Norwegian', 'no'),
    'NNY' : WikipediaLanguage('Norwegian Nynorsk', 'nn'),
    'NOV' : WikipediaLanguage('Novial', 'nov'),
    'OCC' : WikipediaLanguage('Occitan', 'oc'),
    'ODI' : WikipediaLanguage('Odia', 'or'),
    'OEN' : WikipediaLanguage('Old English', 'ang'),
    'ORO' : WikipediaLanguage('Oromo', 'om'),
    'OSS' : WikipediaLanguage('Ossetian', 'os'),
    'PAO' : WikipediaLanguage('Pa\'O', 'blk'),
    'PAW' : WikipediaLanguage('Paiwan', 'pwn'),
    'PGE' : WikipediaLanguage('Palatine German', 'pfl'),
    'PAL' : WikipediaLanguage('Pali', 'pi'),
    'PMP' : WikipediaLanguage('Pampanga', 'pam'),
    'PAN' : WikipediaLanguage('Pangasinan', 'pag'),
    'PAP' : WikipediaLanguage('Papiamento', 'pap'),
    'PSH' : WikipediaLanguage('Pashto', 'ps'),
    'PEG' : WikipediaLanguage('Pennsylvania German', 'pdc'),
    'PER' : WikipediaLanguage('Persian', 'fa'),
    'PIC' : WikipediaLanguage('Picard', 'pcd'),
    'PID' : WikipediaLanguage('Piedmontese', 'pms'),
    'POL' : WikipediaLanguage('Polish', 'pl'),
    'PON' : WikipediaLanguage('Pontic', 'pnt'),
    'POR' : WikipediaLanguage('Portuguese', 'pt'),
    'PUN' : WikipediaLanguage('Punjabi', 'pa'),
    'QUE' : WikipediaLanguage('Quechua', 'qu'),
    'ROU' : WikipediaLanguage('Romanian', 'ro'),
    'ROM' : WikipediaLanguage('Romansh', 'rm'),
    'RUN' : WikipediaLanguage('Rundi', 'rn'),
    'RUB' : WikipediaLanguage('Buryat', 'bxr'),
    'RUS' : WikipediaLanguage('Russian', 'ru'),
    'RSN' : WikipediaLanguage('Rusyn', 'rue'),
    'SAK' : WikipediaLanguage('Sakizaya', 'szy'),
    'SAM' : WikipediaLanguage('Samoan', 'sm'),
    'SMG' : WikipediaLanguage('Samogitian', 'bat-smg'),
    'SAN' : WikipediaLanguage('Sango', 'sg'),
    'SNS' : WikipediaLanguage('Sanskrit', 'sa'),
    'SAT' : WikipediaLanguage('Santali', 'sat'),
    'SAR' : WikipediaLanguage('Saraiki', 'skr'),
    'SRD' : WikipediaLanguage('Sardinian', 'sc'),
    'SFR' : WikipediaLanguage('Saterland Frisian', 'stq'),
    'SCO' : WikipediaLanguage('Scots', 'sco'),
    'SCG' : WikipediaLanguage('Scottish Gaelic', 'gd'),
    'SRB' : WikipediaLanguage('Serbian', 'sr'),
    'SRC' : WikipediaLanguage('Serbo-Croatian', 'sh'),
    'SHA' : WikipediaLanguage('Shan', 'shn'),
    'SHN' : WikipediaLanguage('Shona', 'sn'),
    'SIC' : WikipediaLanguage('Sicilian', 'scn'),
    'SIL' : WikipediaLanguage('Silesian', 'szl'),
    'SEN' : WikipediaLanguage('Simple English', 'simple'),
    'SND' : WikipediaLanguage('Sindhi', 'sd'),
    'SNH' : WikipediaLanguage('Sinhala', 'si'),
    'SVK' : WikipediaLanguage('Slovak', 'sk'),
    'SVN' : WikipediaLanguage('Slovenian', 'sl'),
    'SOM' : WikipediaLanguage('Somali', 'so'),
    'SAZ' : WikipediaLanguage('South Azerbaijani', 'azb'),
    'SAL' : WikipediaLanguage('Southern Altai', 'alt'),
    'SSO' : WikipediaLanguage('Southern Sotho', 'st'),
    'ESP' : WikipediaLanguage('Spanish', 'es'),
    'SRT' : WikipediaLanguage('Sranan Tongo', 'srn'),
    'SUN' : WikipediaLanguage('Sundanese', 'su'),
    'SWA' : WikipediaLanguage('Swahili', 'sw'),
    'SWT' : WikipediaLanguage('Swati', 'ss'),
    'SWE' : WikipediaLanguage('Swedish', 'sv'),
    'TGL' : WikipediaLanguage('Tagalog', 'tl'),
    'THT' : WikipediaLanguage('Tahitian', 'ty'),
    'TJK' : WikipediaLanguage('Tajik', 'tg'),
    'TAM' : WikipediaLanguage('Tamil', 'ta'),
    'TAR' : WikipediaLanguage('Tarantino', 'roa-tara'),
    'TAT' : WikipediaLanguage('Tatar', 'tt'),
    'TAY' : WikipediaLanguage('Tayal', 'tay'),
    'TEL' : WikipediaLanguage('Telugu', 'te'),
    'TET' : WikipediaLanguage('Tetum', 'tet'),
    'THA' : WikipediaLanguage('Thai', 'th'),
    'TIB' : WikipediaLanguage('Tibetan', 'bo'),
    'TIG' : WikipediaLanguage('Tigrinya', 'ti'),
    'TKP' : WikipediaLanguage('Tok Pisin', 'tpi'),
    'TGA' : WikipediaLanguage('Tongan', 'to'),
    'TSO' : WikipediaLanguage('Tsonga', 'ts'),
    'TSW' : WikipediaLanguage('Tswana', 'tn'),
    'TUL' : WikipediaLanguage('Tulu', 'tcy'),
    'TUM' : WikipediaLanguage('Tumbuka', 'tum'),
    'TUR' : WikipediaLanguage('Turkish', 'tr'),
    'TRK' : WikipediaLanguage('Turkmen', 'tk'),
    'TUV' : WikipediaLanguage('Tuvan', 'tyv'),
    'TWI' : WikipediaLanguage('Twi', 'tw'),
    'TYA' : WikipediaLanguage('Tyap', 'kcg'),
    'UDM' : WikipediaLanguage('Udmurt', 'udm'),
    'UKR' : WikipediaLanguage('Ukrainian', 'uk'),
    'USO' : WikipediaLanguage('Upper Sorbian', 'hsb'),
    'URD' : WikipediaLanguage('Urdu', 'ur'),
    'UYG' : WikipediaLanguage('Uyghur', 'ug'),
    'UZB' : WikipediaLanguage('Uzbek', 'uz'),
    'VED' : WikipediaLanguage('Venda', 've'),
    'VEN' : WikipediaLanguage('Venetian', 'vec'),
    'VEP' : WikipediaLanguage('Veps', 'vep'),
    'VIE' : WikipediaLanguage('Vietnamese', 'vi'),
    'VRO' : WikipediaLanguage('Vlax Romani', 'rmy'),
    'VLP' : WikipediaLanguage('Volapuk', 'vo'),
    'VOR' : WikipediaLanguage('Voro', 'fiu-vro'),
    'WLN' : WikipediaLanguage('Walloon', 'wa'),
    'WRY' : WikipediaLanguage('Waray', 'war'),
    'WAY' : WikipediaLanguage('Wayuu', 'guc'),
    'WAL' : WikipediaLanguage('Welsh', 'cy'),
    'WFL' : WikipediaLanguage('West Flemish', 'vls'),
    'WAR' : WikipediaLanguage('Western Armenian', 'hyw'),
    'WFR' : WikipediaLanguage('Western Frisian', 'fy'),
    'WMR' : WikipediaLanguage('Western Mari', 'mrj'),
    'WPU' : WikipediaLanguage('Western Punjabi', 'pnb'),
    'WOL' : WikipediaLanguage('Wolof', 'wo'),
    'WUC' : WikipediaLanguage('Wu Chinese', 'wuu'),
    'XHO' : WikipediaLanguage('Xhosa', 'xh'),
    'YAK' : WikipediaLanguage('Yakut', 'sah'),
    'YID' : WikipediaLanguage('Yiddish', 'yi'),
    'YOR' : WikipediaLanguage('Yoruba', 'yo'),
    'ZAZ' : WikipediaLanguage('Zazaki', 'diq'),
    'ZEE' : WikipediaLanguage('Zeelandic', 'zea'),
    'ZHU' : WikipediaLanguage('Zhuang', 'za'),
    'ZUL' : WikipediaLanguage('Zulu', 'zu')
}
